package jtech.shopzone.controller.dal.bean;
// Generated Mar 16, 2018 2:19:44 PM by Hibernate Tools 4.3.1



/**
 * UserInterestsId generated by hbm2java
 */
public class UserInterestsId  implements java.io.Serializable {


     private int userId;
     private String interestName;

    public UserInterestsId() {
    }

    public UserInterestsId(int userId, String interestName) {
       this.userId = userId;
       this.interestName = interestName;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getInterestName() {
        return this.interestName;
    }
    
    public void setInterestName(String interestName) {
        this.interestName = interestName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserInterestsId) ) return false;
		 UserInterestsId castOther = ( UserInterestsId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && ( (this.getInterestName()==castOther.getInterestName()) || ( this.getInterestName()!=null && castOther.getInterestName()!=null && this.getInterestName().equals(castOther.getInterestName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + ( getInterestName() == null ? 0 : this.getInterestName().hashCode() );
         return result;
   }   


}


