package jtech.shopzone.model.dal.beans;
// Generated Mar 16, 2018 1:04:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * AdminInfo generated by hbm2java
 */
public class AdminInfo  implements java.io.Serializable {


     private BigDecimal adminId;
     private String email;
     private String firstName;
     private String lastName;
     private String password;

    public AdminInfo() {
    }

	
    public AdminInfo(BigDecimal adminId) {
        this.adminId = adminId;
    }
    public AdminInfo(BigDecimal adminId, String email, String firstName, String lastName, String password) {
       this.adminId = adminId;
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.password = password;
    }
   
    public BigDecimal getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(BigDecimal adminId) {
        this.adminId = adminId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


