package jtech.shopzone.model.dal.beans;
// Generated Mar 16, 2018 1:04:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductsCategory generated by hbm2java
 */
public class ProductsCategory  implements java.io.Serializable {



     private BigDecimal categoryId;
     private String categoryName;
     private Set productsInfos = new HashSet(0);

    public ProductsCategory() {
    }

	
    public ProductsCategory(BigDecimal categoryId, String categoryName) {
        this.categoryId = categoryId;
        this.categoryName = categoryName;
    }
    public ProductsCategory(BigDecimal categoryId, String categoryName, Set productsInfos) {
       this.categoryId = categoryId;
       this.categoryName = categoryName;
       this.productsInfos = productsInfos;
    }
   
    public BigDecimal getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(BigDecimal categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getProductsInfos() {
        return this.productsInfos;
    }
    
    public void setProductsInfos(Set productsInfos) {
        this.productsInfos = productsInfos;
    }




}


