package jtech.shopzone.model.dal.beans;
// Generated Mar 16, 2018 1:04:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductsInfo generated by hbm2java
 */
public class ProductsInfo  implements java.io.Serializable {


     private BigDecimal productId;
     private ProductsCategory productsCategory;
     private String productName;
     private BigDecimal price;
     private BigDecimal quantity;
     private String description;
     private String img;
     private BigDecimal deletedFlg;
     private Set shoppingCarts = new HashSet(0);
     private Set userProductses = new HashSet(0);

    public ProductsInfo() {
    }

	
    public ProductsInfo(BigDecimal productId, String productName, BigDecimal price, BigDecimal quantity, BigDecimal deletedFlg) {
        this.productId = productId;
        this.productName = productName;
        this.price = price;
        this.quantity = quantity;
        this.deletedFlg = deletedFlg;
    }
    public ProductsInfo(BigDecimal productId, ProductsCategory productsCategory, String productName, BigDecimal price, BigDecimal quantity, String description, String img, BigDecimal deletedFlg, Set shoppingCarts, Set userProductses) {
       this.productId = productId;
       this.productsCategory = productsCategory;
       this.productName = productName;
       this.price = price;
       this.quantity = quantity;
       this.description = description;
       this.img = img;
       this.deletedFlg = deletedFlg;
       this.shoppingCarts = shoppingCarts;
       this.userProductses = userProductses;
    }
   
    public BigDecimal getProductId() {
        return this.productId;
    }
    
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }
    public ProductsCategory getProductsCategory() {
        return this.productsCategory;
    }
    
    public void setProductsCategory(ProductsCategory productsCategory) {
        this.productsCategory = productsCategory;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public BigDecimal getDeletedFlg() {
        return this.deletedFlg;
    }
    
    public void setDeletedFlg(BigDecimal deletedFlg) {
        this.deletedFlg = deletedFlg;
    }
    public Set getShoppingCarts() {
        return this.shoppingCarts;
    }
    
    public void setShoppingCarts(Set shoppingCarts) {
        this.shoppingCarts = shoppingCarts;
    }
    public Set getUserProductses() {
        return this.userProductses;
    }
    
    public void setUserProductses(Set userProductses) {
        this.userProductses = userProductses;
    }




}


