package jtech.shopzone.model.dal.beans;
// Generated Mar 16, 2018 1:04:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ShoppingCart generated by hbm2java
 */
public class ShoppingCart  implements java.io.Serializable {


     private ShoppingCartId id;
     private ProductsInfo productsInfo;
     private Userinfo userinfo;
     private BigDecimal quantity;

    public ShoppingCart() {
    }

	
    public ShoppingCart(ShoppingCartId id, ProductsInfo productsInfo, Userinfo userinfo) {
        this.id = id;
        this.productsInfo = productsInfo;
        this.userinfo = userinfo;
    }
    public ShoppingCart(ShoppingCartId id, ProductsInfo productsInfo, Userinfo userinfo, BigDecimal quantity) {
       this.id = id;
       this.productsInfo = productsInfo;
       this.userinfo = userinfo;
       this.quantity = quantity;
    }
   
    public ShoppingCartId getId() {
        return this.id;
    }
    
    public void setId(ShoppingCartId id) {
        this.id = id;
    }
    public ProductsInfo getProductsInfo() {
        return this.productsInfo;
    }
    
    public void setProductsInfo(ProductsInfo productsInfo) {
        this.productsInfo = productsInfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }




}


