package jtech.shopzone.model.dal.beans;
// Generated Mar 16, 2018 1:04:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * UserProducts generated by hbm2java
 */
public class UserProducts  implements java.io.Serializable {


     private UserProductsId id;
     private ProductsInfo productsInfo;
     private Userinfo userinfo;
     private BigDecimal quantity;
     private Date orderDate;
     private BigDecimal price;

    public UserProducts() {
    }

	
    public UserProducts(UserProductsId id, ProductsInfo productsInfo, Userinfo userinfo) {
        this.id = id;
        this.productsInfo = productsInfo;
        this.userinfo = userinfo;
    }
    public UserProducts(UserProductsId id, ProductsInfo productsInfo, Userinfo userinfo, BigDecimal quantity, Date orderDate, BigDecimal price) {
       this.id = id;
       this.productsInfo = productsInfo;
       this.userinfo = userinfo;
       this.quantity = quantity;
       this.orderDate = orderDate;
       this.price = price;
    }
   
    public UserProductsId getId() {
        return this.id;
    }
    
    public void setId(UserProductsId id) {
        this.id = id;
    }
    public ProductsInfo getProductsInfo() {
        return this.productsInfo;
    }
    
    public void setProductsInfo(ProductsInfo productsInfo) {
        this.productsInfo = productsInfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }




}


