package jtech.shopzone.model.dal.beans;
// Generated Mar 16, 2018 1:04:09 AM by Hibernate Tools 4.3.1



/**
 * UserInterests generated by hbm2java
 */
public class UserInterests  implements java.io.Serializable {


     private UserInterestsId id;
     private Userinfo userinfo;

    public UserInterests() {
    }

    public UserInterests(UserInterestsId id, Userinfo userinfo) {
       this.id = id;
       this.userinfo = userinfo;
    }
   
    public UserInterestsId getId() {
        return this.id;
    }
    
    public void setId(UserInterestsId id) {
        this.id = id;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }




}


