package jtech.shopzone.model.dal.beans;
// Generated Mar 16, 2018 1:04:09 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * UserInterestsId generated by hbm2java
 */
public class UserInterestsId  implements java.io.Serializable {


     private BigDecimal userId;
     private String interestName;

    public UserInterestsId() {
    }

    public UserInterestsId(BigDecimal userId, String interestName) {
       this.userId = userId;
       this.interestName = interestName;
    }
   
    public BigDecimal getUserId() {
        return this.userId;
    }
    
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }
    public String getInterestName() {
        return this.interestName;
    }
    
    public void setInterestName(String interestName) {
        this.interestName = interestName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserInterestsId) ) return false;
		 UserInterestsId castOther = ( UserInterestsId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getInterestName()==castOther.getInterestName()) || ( this.getInterestName()!=null && castOther.getInterestName()!=null && this.getInterestName().equals(castOther.getInterestName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getInterestName() == null ? 0 : this.getInterestName().hashCode() );
         return result;
   }   


}


