package jtech.shopzone.model.dal.bean;
// Generated Mar 16, 2018 2:19:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductsCategory generated by hbm2java
 */
public class ProductsCategory  implements java.io.Serializable {


     private Integer categoryId;
     private String categoryName;
     private Set productsInfos = new HashSet(0);

    public ProductsCategory() {
    }

	
    public ProductsCategory(String categoryName) {
        this.categoryName = categoryName;
    }
    public ProductsCategory(String categoryName, Set productsInfos) {
       this.categoryName = categoryName;
       this.productsInfos = productsInfos;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public Set getProductsInfos() {
        return this.productsInfos;
    }
    
    public void setProductsInfos(Set productsInfos) {
        this.productsInfos = productsInfos;
    }




}


