package jtech.shopzone.model.dal.bean;
// Generated Mar 16, 2018 2:19:44 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ProductsInfo generated by hbm2java
 */
public class ProductsInfo  implements java.io.Serializable {


     private Integer productId;
     private ProductsCategory productsCategory;
     private String productName;
     private long price;
     private int quantity;
     private String description;
     private String img;
     private int deletedFlg;
     private Set shoppingCarts = new HashSet(0);
     private Set userProductses = new HashSet(0);

    public ProductsInfo() {
    }

	
    public ProductsInfo(ProductsCategory productsCategory, String productName, long price, int quantity, int deletedFlg) {
        this.productsCategory = productsCategory;
        this.productName = productName;
        this.price = price;
        this.quantity = quantity;
        this.deletedFlg = deletedFlg;
    }
    public ProductsInfo(ProductsCategory productsCategory, String productName, long price, int quantity, String description, String img, int deletedFlg, Set shoppingCarts, Set userProductses) {
       this.productsCategory = productsCategory;
       this.productName = productName;
       this.price = price;
       this.quantity = quantity;
       this.description = description;
       this.img = img;
       this.deletedFlg = deletedFlg;
       this.shoppingCarts = shoppingCarts;
       this.userProductses = userProductses;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public ProductsCategory getProductsCategory() {
        return this.productsCategory;
    }
    
    public void setProductsCategory(ProductsCategory productsCategory) {
        this.productsCategory = productsCategory;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public int getDeletedFlg() {
        return this.deletedFlg;
    }
    
    public void setDeletedFlg(int deletedFlg) {
        this.deletedFlg = deletedFlg;
    }
    public Set getShoppingCarts() {
        return this.shoppingCarts;
    }
    
    public void setShoppingCarts(Set shoppingCarts) {
        this.shoppingCarts = shoppingCarts;
    }
    public Set getUserProductses() {
        return this.userProductses;
    }
    
    public void setUserProductses(Set userProductses) {
        this.userProductses = userProductses;
    }




}


