package jtech.shopzone.model.dal.bean;
// Generated Mar 16, 2018 2:19:44 PM by Hibernate Tools 4.3.1



/**
 * ShoppingCart generated by hbm2java
 */
public class ShoppingCart  implements java.io.Serializable {


     private ShoppingCartId id;
     private ProductsInfo productsInfo;
     private Userinfo userinfo;
     private int quantity;

    public ShoppingCart() {
    }

    public ShoppingCart(ShoppingCartId id, ProductsInfo productsInfo, Userinfo userinfo, int quantity) {
       this.id = id;
       this.productsInfo = productsInfo;
       this.userinfo = userinfo;
       this.quantity = quantity;
    }
   
    public ShoppingCartId getId() {
        return this.id;
    }
    
    public void setId(ShoppingCartId id) {
        this.id = id;
    }
    public ProductsInfo getProductsInfo() {
        return this.productsInfo;
    }
    
    public void setProductsInfo(ProductsInfo productsInfo) {
        this.productsInfo = productsInfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


