package jtech.shopzone.model.dal.bean;
// Generated Mar 16, 2018 2:19:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UserProducts generated by hbm2java
 */
public class UserProducts  implements java.io.Serializable {


     private UserProductsId id;
     private ProductsInfo productsInfo;
     private Userinfo userinfo;
     private int quantity;
     private Date orderDate;
     private long price;

    public UserProducts() {
    }

	
    public UserProducts(UserProductsId id, ProductsInfo productsInfo, Userinfo userinfo, int quantity, long price) {
        this.id = id;
        this.productsInfo = productsInfo;
        this.userinfo = userinfo;
        this.quantity = quantity;
        this.price = price;
    }
    public UserProducts(UserProductsId id, ProductsInfo productsInfo, Userinfo userinfo, int quantity, Date orderDate, long price) {
       this.id = id;
       this.productsInfo = productsInfo;
       this.userinfo = userinfo;
       this.quantity = quantity;
       this.orderDate = orderDate;
       this.price = price;
    }
   
    public UserProductsId getId() {
        return this.id;
    }
    
    public void setId(UserProductsId id) {
        this.id = id;
    }
    public ProductsInfo getProductsInfo() {
        return this.productsInfo;
    }
    
    public void setProductsInfo(ProductsInfo productsInfo) {
        this.productsInfo = productsInfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }




}


